//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCC_SP_Quy2
    {
        public string MaNCC { get; set; }
        public string TenNCC { get; set; }
        public Nullable<int> Số_Lượng_Nhập { get; set; }
    }
}
