//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPBanNhieuNhatThang2Nam2019
    {
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> DonGiaBan { get; set; }
        public string KieuDang { get; set; }
        public string ManHinh { get; set; }
        public string Camera { get; set; }
        public string BoNhoTrong { get; set; }
        public string HeDieuHanh { get; set; }
        public string CPU { get; set; }
        public string Pin { get; set; }
        public Nullable<int> So_lan_ban { get; set; }
    }
}
